name: Custom

on:
  schedule:
    - cron: 0 4 * * * # 4:00 UTC everyday
  workflow_dispatch:

permissions: {}

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-26.04
    strategy:
      matrix:
        python-version: ["3.14"]
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: true

      - name: setup project with mise
        id: setup-mise
        uses: jdx/mise-action@c2a87611a18de5b3828c5652fe268e992400cb5c # v4.3.0
        with:
          install: true
          cache: true
          cache_key_prefix: "build"
          tool_versions: |
            python ${{ matrix.python-version }}
            uv latest

      - name: build my custom calendar
        run: mise run "build:custom"

      - name: check release changes
        id: check_changes
        run: if [[ $(git diff --name-only HEAD) == *"output/vndb.csv"* ]]; then echo "changes=true" > "$GITHUB_OUTPUT"; else echo "changes=false" > "$GITHUB_OUTPUT"; fi

      - name: commit files
        if: ${{ steps.check_changes.outputs.changes == 'true' }}
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -u
          git commit -m "ics: update calendar" -a
          git push origin main
