name: Release

on:
  schedule:
    - cron: 0 4 * * * # 4:00 UTC everyday
  workflow_dispatch:

permissions: {}

jobs:
  build:
    permissions:
      contents: write # required to make release
    runs-on: ubuntu-26.04
    strategy:
      matrix:
        python-version: ["3.14"]
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: true

      - name: setup project with mise
        id: setup-mise
        uses: jdx/mise-action@c2a87611a18de5b3828c5652fe268e992400cb5c # v4.3.0
        with:
          install: true
          cache: true
          cache_key_prefix: "build"
          tool_versions: |
            python ${{ matrix.python-version }}
            uv latest

      - name: build VNDB calendar with en & ja releases
        run: mise run "build:en"
      - name: upload to release
        run: gh release upload "${TAG}" --clobber output/vndb-*
        env:
          GH_TOKEN: ${{ github.token }}
          TAG: en

      - name: build VNDB calendar with unofficial en patch released in 2026
        run: mise run "build:enpatch"
      - name: upload to release
        run: gh release upload "${TAG}" --clobber output/vndb-*
        env:
          GH_TOKEN: ${{ github.token }}
          TAG: enpatch

      # - name: build VNDB calendar with zh & ja releases
      #   run: mise run "build:zh"
      # - name: upload to release
      #   run: gh release upload "${TAG}" --clobber output/vndb-*
      #   env:
      #     GH_TOKEN: ${{ github.token }}
      #     TAG: zh

      - name: build VNDB calendar with unofficial zh patch released in 2026
        run: mise run "build:zhpatch"
      - name: upload to release
        run: gh release upload "${TAG}" --clobber output/vndb-*
        env:
          GH_TOKEN: ${{ github.token }}
          TAG: zhpatch
