name: Release

on:
  schedule:
    - cron: 0 4 * * * # 4:00 UTC everyday
  workflow_dispatch:

permissions:
  contents: write # required to make release

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: get site-packages path
        id: site_packages
        run: echo "site_dir=$(python -c 'import site; print(site.getsitepackages()[0])')" > "$GITHUB_OUTPUT"

      - name: cache installed packages
        uses: actions/cache@v4
        with:
          path: ${{ steps.site_packages.outputs.site_dir }}
          key: ${{ runner.os }}-pip-${{ matrix.python-version }}-${{ hashFiles('**/requirements.txt') }}
          restore-keys: ${{ runner.os }}-pip-

      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: make en & ja release calendar
        run: python vndb-calendar.py -f "0572171_4YsVe122gen2gjaN48721gwcomplete-" -t 0 -d 1

      - name: upload artifact to release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: True
          prerelease: False
          tag: en
          omitBody: True
          omitBodyDuringUpdate: True
          omitNameDuringUpdate: True
          artifacts: output/vndb-*
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: make zh & ja release calendar
        run: python vndb-calendar.py -f "0572171_4YsVe132gja2wzh_dHans-2wzh_dHant-N48721gwcomplete-" -t 0 -d 1

      - name: upload artifact to release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: True
          prerelease: False
          tag: zh
          omitBody: True
          omitBodyDuringUpdate: True
          omitNameDuringUpdate: True
          artifacts: output/vndb-*
          token: ${{ secrets.GITHUB_TOKEN }}
