name: Test

on:
  push:
    branches:
      - main
    paths-ignore:
      - output/**
      - "**.md"
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.13", "3.14"]
    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false

      - name: setup project with mise
        id: setup-mise
        uses: jdx/mise-action@v3
        with:
          install: true
          cache: true
          tool_versions: |
            python ${{ matrix.python-version }}
            uv latest

      - run: mise run default
