name: Test

on:
  push:
    branches:
      - main
    paths-ignore:
      - output/**
      - "**.md"
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read

jobs:
  test:
    runs-on: ubuntu-26.04
    strategy:
      matrix:
        python-version: ["3.13", "3.14", "3.15-dev"]
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: setup project with mise
        id: setup-mise
        uses: jdx/mise-action@c2a87611a18de5b3828c5652fe268e992400cb5c # v4.3.0
        with:
          install: true
          cache: true
          cache_key_prefix: "test"
          tool_versions: |
            python ${{ matrix.python-version }}
            uv latest

      - run: mise run default
